"use client";

import { useActionState } from "react";
import { useRouter } from "next/navigation";
import { saveAdminService } from "@/lib/actions";
import type { AdminService, AdminWorkspace } from "@/lib/admin";

const initialState: { error?: string; success?: boolean } = {};

function translation(service: AdminService | undefined, code: string) {
  return service?.translations.find((item) => item.language_code === code);
}

function rulesJson(service: AdminService | undefined) {
  return JSON.stringify((service?.rules ?? []).map((rule) => ({ question_type: rule.question_type, question_text: rule.question_text, options: rule.options, sort_order: rule.sort_order, status: rule.status, translations: Object.fromEntries(rule.translations.map((item) => [item.language_code, { question_text: item.question_text, option_labels: item.option_labels }])) })), null, 2);
}

export function AdminServiceForm({ workspace, selectedService }: { workspace: AdminWorkspace; selectedService?: AdminService }) {
  const [state, formAction, pending] = useActionState(saveAdminService, initialState);
  const router = useRouter();
  const english = translation(selectedService, "en");
  const hindi = translation(selectedService, "hi");
  const selectedDocumentIds = new Set(selectedService?.documents.map((document) => document.document_type_id));
  return <form action={formAction} className="space-y-8" aria-describedby="admin-form-help">
    <p id="admin-form-help" className="text-sm text-slate-600">Every save requires an explicit service status and source status. Source edits record the signed-in administrator as the verifier.</p>
    {state.error && <p role="alert" className="rounded-md border border-rose-200 bg-rose-50 p-4 text-rose-800">{state.error}</p>}
    {state.success && <p role="status" className="rounded-md border border-emerald-200 bg-emerald-50 p-4 text-emerald-800">Service saved and audit log recorded.</p>}
    <input type="hidden" name="service_id" value={selectedService?.id ?? ""} />
    <input type="hidden" name="source_id" value={selectedService?.source?.id ?? ""} />
    <fieldset className="grid gap-4 rounded-xl border border-slate-200 bg-white p-6 md:grid-cols-2"><legend className="px-2 text-lg font-semibold">Service record</legend>
      <label className="text-sm font-medium">Existing service<select name="service_id_select" defaultValue={selectedService?.id ?? ""} onChange={(event) => { if (event.target.value) router.push(`/admin?service=${event.target.value}`); }} className="mt-2 min-h-11 w-full rounded-md border border-slate-300 bg-white px-3"><option value="">Create new service</option>{workspace.services.map((service) => <option key={service.id} value={service.id}>{service.slug}</option>)}</select></label>
      <label className="text-sm font-medium">Slug<input name="slug" required defaultValue={selectedService?.slug ?? ""} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" className="mt-2 min-h-11 w-full rounded-md border border-slate-300 px-3" /></label>
      <label className="text-sm font-medium">State<select name="state_id" required defaultValue={selectedService?.state_id ?? ""} className="mt-2 min-h-11 w-full rounded-md border border-slate-300 bg-white px-3"><option value="">Choose state</option>{workspace.states.map((state) => <option key={state.id} value={state.id}>{state.name} ({state.code})</option>)}</select></label>
      <label className="text-sm font-medium">Category<select name="category_id" required defaultValue={selectedService?.category_id ?? ""} className="mt-2 min-h-11 w-full rounded-md border border-slate-300 bg-white px-3"><option value="">Choose category</option>{workspace.categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label>
      <label className="text-sm font-medium">Department<select name="department_id" required defaultValue={selectedService?.department_id ?? ""} className="mt-2 min-h-11 w-full rounded-md border border-slate-300 bg-white px-3"><option value="">Choose department</option>{workspace.departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select></label>
      <label className="text-sm font-medium">Service status<select name="status" required defaultValue={selectedService?.status ?? ""} className="mt-2 min-h-11 w-full rounded-md border border-slate-300 bg-white px-3"><option value="">Choose status</option><option value="draft">draft</option><option value="published">published</option><option value="inactive">inactive</option></select></label>
    </fieldset>
    <fieldset className="grid gap-6 rounded-xl border border-slate-200 bg-white p-6 md:grid-cols-2"><legend className="px-2 text-lg font-semibold">Translations</legend>{(["en", "hi"] as const).map((code) => { const item = code === "en" ? english : hindi; return <div key={code} className="space-y-3"><h2 className="font-medium">{code === "en" ? "English" : "Hindi"}</h2><input type="hidden" name={`${code}_language_code`} value={code} /><label className="block text-sm font-medium">Name<input name={`${code}_name`} required defaultValue={item?.name ?? ""} className="mt-1 min-h-11 w-full rounded-md border border-slate-300 px-3" /></label><label className="block text-sm font-medium">Short description<textarea name={`${code}_short_description`} defaultValue={item?.short_description ?? ""} className="mt-1 min-h-24 w-full rounded-md border border-slate-300 p-3" /></label><label className="block text-sm font-medium">Full description<textarea name={`${code}_full_description`} defaultValue={item?.full_description ?? ""} className="mt-1 min-h-24 w-full rounded-md border border-slate-300 p-3" /></label><label className="block text-sm font-medium">Eligibility text<textarea name={`${code}_eligibility_text`} defaultValue={item?.eligibility_text ?? ""} className="mt-1 min-h-24 w-full rounded-md border border-slate-300 p-3" /></label><label className="block text-sm font-medium">How to apply<textarea name={`${code}_how_to_apply_text`} defaultValue={item?.how_to_apply_text ?? ""} className="mt-1 min-h-24 w-full rounded-md border border-slate-300 p-3" /></label></div>; })}</fieldset>
    <fieldset className="rounded-xl border border-slate-200 bg-white p-6"><legend className="px-2 text-lg font-semibold">Documents</legend><div className="mt-2 grid gap-3 md:grid-cols-2">{workspace.documentTypes.map((document) => <label key={document.id} className="flex min-h-11 items-center gap-3 rounded-md border border-slate-200 p-3"><input type="checkbox" name="document_type_id" value={document.id} defaultChecked={selectedDocumentIds.has(document.id)} className="size-5 accent-teal-700" /><span>{document.name}</span><select name={`required_${document.id}`} defaultValue={selectedService?.documents.find((item) => item.document_type_id === document.id)?.is_required ? "on" : "off"} className="ml-auto min-h-11 rounded border border-slate-300 px-2 text-sm"><option value="on">Required</option><option value="off">Optional</option></select></label>)}</div><p className="mt-4 text-sm text-slate-600">Add new document types through the database until a dedicated document-type editor is needed.</p></fieldset>
    <fieldset className="grid gap-4 rounded-xl border border-slate-200 bg-white p-6 md:grid-cols-2"><legend className="px-2 text-lg font-semibold">Official source</legend><label className="text-sm font-medium">Source URL<input name="source_url" type="url" required defaultValue={selectedService?.source?.source_url ?? ""} className="mt-2 min-h-11 w-full rounded-md border border-slate-300 px-3" /></label><label className="text-sm font-medium">Source title<input name="source_title" required defaultValue={selectedService?.source?.source_title ?? ""} className="mt-2 min-h-11 w-full rounded-md border border-slate-300 px-3" /></label><label className="text-sm font-medium">Verified date<input name="verified_at" type="date" defaultValue={selectedService?.source?.verified_at?.slice(0, 10) ?? ""} className="mt-2 min-h-11 w-full rounded-md border border-slate-300 px-3" /></label><label className="text-sm font-medium">Source status<select name="source_status" required defaultValue={selectedService?.source?.status ?? ""} className="mt-2 min-h-11 w-full rounded-md border border-slate-300 bg-white px-3"><option value="">Choose status</option><option value="verified">verified</option><option value="needs_review">needs_review</option><option value="outdated">outdated</option><option value="archived">archived</option></select></label></fieldset>
    <fieldset className="rounded-xl border border-slate-200 bg-white p-6"><legend className="px-2 text-lg font-semibold">Eligibility rules</legend><label className="block text-sm font-medium">Rules JSON<textarea name="eligibility_rules_json" defaultValue={rulesJson(selectedService)} className="mt-2 min-h-56 w-full rounded-md border border-slate-300 p-3 font-mono text-sm" aria-describedby="rules-help" /></label><p id="rules-help" className="mt-2 text-sm text-slate-600">Use the existing rule shape: question_type, question_text, options, sort_order, status, and translations keyed by en/hi. Rules default to review-needed only when explicitly included with that status.</p></fieldset>
    <button type="submit" disabled={pending} className="min-h-11 rounded-md bg-teal-700 px-6 py-3 font-medium text-white hover:bg-teal-800 disabled:opacity-50">{pending ? "Saving..." : "Save service"}</button>
  </form>;
}
