"use client";

import Link from "next/link";
import { useState, useTransition } from "react";
import { saveEligibilityResult } from "@/lib/actions";
import type { EligibilityRule } from "@/lib/data";
import { trustCopy } from "@/config/content";

export function EligibilityChecker({ serviceId, rules, languageCode }: { serviceId: string; rules: EligibilityRule[]; languageCode: string }) {
  const [step, setStep] = useState(0);
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [finished, setFinished] = useState(false);
  const [saveMessage, setSaveMessage] = useState("");
  const [pending, startTransition] = useTransition();
  const rule = rules[step];
  const translation = rule?.translations.find((item) => item.language_code === languageCode) ?? rule?.translations.find((item) => item.language_code === "en") ?? rule?.translations[0];
  const options = translation ? rule.options.map((option) => ({ value: option.value, label: translation.option_labels[option.value] ?? option.label })) : [];
  if (!rules.length) return <section className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="text-2xl font-semibold">Eligibility questions</h2><p className="mt-3 text-slate-600">No eligibility questions are listed for this service yet.</p></section>;
  if (finished) return <section className="rounded-xl border border-amber-200 bg-amber-50 p-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-amber-800">Review needed</p><h2 className="mt-2 text-2xl font-semibold text-slate-900">Your answers are a starting point</h2><p className="mt-3 leading-7 text-slate-700">Based on what you shared, you may be able to continue with this service. Please verify the current official requirements before applying.</p><p className="mt-4 text-sm text-slate-700">These questions are marked for review and do not provide a legal or definitive eligibility determination.</p><p className="mt-4 text-sm font-medium text-slate-700">{trustCopy.independentDisclaimer}</p>{saveMessage ? <p className="mt-4 text-sm font-medium text-teal-800">{saveMessage}</p> : <div className="mt-5 flex flex-wrap gap-3"><button type="button" disabled={pending} onClick={() => startTransition(async () => { const result = await saveEligibilityResult(serviceId, answers); setSaveMessage(result.ok ? "Your result was saved." : result.reason === "unauthenticated" ? "Sign in to save this result and return to it later." : "We could not save this result right now."); })} className="min-h-11 rounded-md bg-teal-700 px-4 py-2 text-sm font-medium text-white hover:bg-teal-800 disabled:opacity-50">Save result</button><Link href={`/auth?next=/services&lang=${languageCode}`} className="inline-flex min-h-11 items-center rounded-md border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700">Sign in</Link></div>}<button type="button" onClick={() => { setFinished(false); setStep(0); }} className="mt-5 block min-h-11 text-sm font-medium text-teal-800 underline underline-offset-4">Start again</button></section>;
  return <section className="rounded-xl border border-slate-200 bg-white p-6"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-teal-700">Eligibility questions</p><h2 className="mt-2 text-2xl font-semibold">Question {step + 1} of {rules.length}</h2></div><span className="text-sm text-slate-500">{Math.round(((step + 1) / rules.length) * 100)}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100" role="progressbar" aria-label={`Eligibility progress: question ${step + 1} of ${rules.length}`} aria-valuemin={1} aria-valuemax={rules.length} aria-valuenow={step + 1}><div className="h-full bg-teal-700 transition-all" style={{ width: `${((step + 1) / rules.length) * 100}%` }} /></div><p className="mt-7 text-lg font-medium leading-7 text-slate-900">{translation?.question_text ?? rule.question_text}</p><div className="mt-5 space-y-3">{options.map((option) => <label key={option.value} className="flex min-h-11 cursor-pointer items-center gap-3 rounded-lg border border-slate-200 p-4 hover:border-teal-700 has-[:focus-visible]:outline-2 has-[:focus-visible]:outline-teal-700"><input type="radio" name={rule.id} value={option.value} checked={answers[rule.id] === option.value} onChange={() => setAnswers((current) => ({ ...current, [rule.id]: option.value }))} className="size-4 accent-teal-700" />{option.label}</label>)}</div><div className="mt-7 flex justify-between gap-3"><button type="button" disabled={step === 0} onClick={() => setStep((current) => current - 1)} className="min-h-11 rounded-md border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 disabled:opacity-40">Back</button><button type="button" disabled={!answers[rule.id]} onClick={() => step === rules.length - 1 ? setFinished(true) : setStep((current) => current + 1)} className="min-h-11 rounded-md bg-teal-700 px-5 py-2 text-sm font-medium text-white hover:bg-teal-800 disabled:opacity-40">{step === rules.length - 1 ? "See guidance" : "Next"}</button></div></section>;
}
